[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf
    storage.path /fluent-bit/storage

[INPUT]
    Name              tail
    Path              /shared/app4.log
    Parser            custom_log
    Tag               app4.log
    DB                /fluent-bit/storage/flb.db
    Refresh_Interval  1
    Skip_Long_Lines   On
    Read_from_Head    true

[FILTER]
    Name    modify
    Match   app4.log
    Add     sourceApp 68749bf41b3c1c89316e359a
    Add     environment development
    Rename  level    logLevel
    Rename  traceid  traceId

[FILTER]
    Name    record_modifier
    Match   app4.log
    Record  application_name app4
    Record  fluent_bit_instance app4

[OUTPUT]
    Name  http
    Match *
    Host  ${PRODUCER_HOST}
    Port  ${PRODUCER_PORT}
    URI   /ingest
    Format json
    Json_date_key timestamp
    Json_date_format iso8601
    Retry_Limit 1000